UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Finland';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Denmark';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Iceland';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Sweden';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Israel';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Netherlands';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Norway';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Luxembourg';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Switzerland';
UPDATE whr_raw SET continent_id = 5 WHERE "Country name" = 'Australia';
UPDATE whr_raw SET continent_id = 5 WHERE "Country name" = 'New Zealand';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Costa Rica';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Kuwait';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Austria';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Canada';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Belgium';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Ireland';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Czechia';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Lithuania';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'United Kingdom';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Slovenia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'United Arab Emirates';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'United States';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Germany';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Mexico';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Uruguay';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'France';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Saudi Arabia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Kosovo';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Singapore';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Taiwan Province of China';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Romania';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'El Salvador';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Estonia';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Poland';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Spain';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Serbia';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Chile';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Bahrain';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Malta';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Panama';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Mauritius';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Kazakhstan';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Cyprus';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Guatemala';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Croatia';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Nicaragua';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Kyrgyzstan';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Moldova';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Ghana';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Belarus';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Thailand';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Uzbekistan';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Jordan';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Hong Kong S.A.R. of China';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Iraq';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Turkiye';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Lebanon';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Russia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Iran';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Azerbaijan';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Nigeria';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Bolivia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Mongolia';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Argentina';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Cameroon';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Bulgaria';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Ivory Coast';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Nepal';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Dominican Republic';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'South Africa';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'China';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Pakistan';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Algeria';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Malaysia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Indonesia';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Paraguay';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Angola';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Gambia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Kenya';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Madagascar';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Ethiopia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Philippines';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Congo (Brazzaville)';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Egypt';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Myanmar';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Guinea';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Benin';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Bangladesh';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Morocco';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Uganda';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Sri Lanka';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Honduras';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Ukraine';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Zimbabwe';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Rwanda';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Georgia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Liberia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Sudan';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Qatar';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Sierra Leone';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'State of Palestine';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Mozambique';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Niger';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Malawi';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Zambia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Comoros';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Lesotho';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Tajikistan';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Burkina Faso';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Namibia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Chad';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Central African Republic';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'South Sudan';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Benin';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Guinea-Bissau';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Botswana';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Eswatini';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Mali';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Armenia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Tanzania';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Syria';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Gabon';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Burundi';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Cameroon';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Congo (Kinshasa)';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Afghanistan';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Yemen';


UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Greece';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Bosnia and Herzegovina';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Italy';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Slovakia';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Portugal';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Hungary';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Montenegro';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'North Macedonia';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Albania';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Libya';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Senegal';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Mauritania';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Tunisia';
UPDATE whr_raw SET continent_id = 1 WHERE "Country name" = 'Togo';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Jamaica';
UPDATE whr_raw SET continent_id = 4 WHERE "Country name" = 'Nicaragua';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Peru';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Brazil';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Ecuador';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Colombia';
UPDATE whr_raw SET continent_id = 6 WHERE "Country name" = 'Venezuela';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Japan';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'South Korea';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Vietnam';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Laos';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'Cambodia';
UPDATE whr_raw SET continent_id = 2 WHERE "Country name" = 'India';
UPDATE whr_raw SET continent_id = 3 WHERE "Country name" = 'Latvia';
